add_rules("mode.debug", "mode.release")
set_encodings("utf-8")
set_policy("build.warning", true)
set_languages("cxxlatest")
set_optimize("fastest")
add_requires("microsoft-detours")
add_requires("ftxui")

target("audiospeedhack")
set_kind("shared")
add_files("src/audiospeedhack.cpp")
add_packages("microsoft-detours")
add_syslinks("dxguid", "ole32", "oleaut32", "mmdevapi", "user32", "uuid")

target("injector")
set_kind("binary")
add_files("src/injector.cpp")
add_packages("ftxui")
add_defines("NOMINMAX")
